### ISSUE TITLE
DropdownRoles bug on mobile

### ISSUE THREAD

**Issue by vscheideck** [SlashBotDiscord/SlashBotLocalization#22]
On a mobile (iOS)
When adding roles using the DropdownRoles, Error message: Interaction failure (in French Echec de l'interaction) and all previous roles are deleted. see screen shot.

![image](https://user-images.githubusercontent.com/16386202/168379446-da33b2e1-951f-4b04-a3db-80e6f65d988b.png)

**Comment by ZeldaFan0225** [comment]
Please do not open issues for the bot, go get support here instead: https://slashbot.de/discord
